# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    orbs:
      heroku: circleci/heroku@0.0.10
    steps:
      # special step to check out source code to working directory
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run:
          name: 'Install Packages'
          command: |
            npm ci
            sudo npm i
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: "Create .env file"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo API_URL=${API_URL} >> .env
              echo API_HOST=${API_HOST} >> .env
              echo HEROKU_APP_NAME=${HEROKU_APP_NAME} >> .env
              echo HEROKU_API_KEY=${HEROKU_API_KEY} >> .env
            fi
      - run: npm run build:prod
workflows:
  version: 2
  build_env:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
                - heroku/deploy-via-git
