export const LIST_HACKER_NEWS_REQUEST = 'LIST_HACKER_NEWS_REQUEST'
export const LIST_HACKER_NEWS_SUCCESS = 'LIST_HACKER_NEWS_SUCCESS'
export const LIST_HACKER_NEWS_FAILURE = 'LIST_HACKER_NEWS_FAILURE'
